# Generated by Django 3.1.7 on 2021-10-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoSeguim', models.IntegerField()),
                ('dniPersona', models.IntegerField()),
                ('estado', models.CharField(choices=[('En preparacion', 'En preparacion'), ('Despachado', 'Despachado'), ('En camino', 'En camino'), ('Entregado', 'Entregado')], max_length=20)),
                ('domicilio_entrega', models.CharField(max_length=200)),
                ('idPaquete', models.IntegerField()),
            ],
            options={
                'db_table': 'envio',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'paquete',
            },
        ),
    ]
