# Generated by Django 3.1.7 on 2021-10-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='codigoSeguim',
            field=models.IntegerField(unique=True),
        ),
    ]
