# Generated by Django 3.1.7 on 2021-11-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0002_auto_20211022_0400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paquete',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='idPaquete',
        ),
        migrations.AddField(
            model_name='envio',
            name='nroVendedor',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
