# Generated by Django 3.1.7 on 2021-11-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0003_auto_20211108_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='nroVendedor',
            field=models.IntegerField(),
        ),
    ]
