# Generated by Django 3.1.7 on 2021-10-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroCuenta', models.IntegerField()),
                ('saldo', models.FloatField()),
            ],
            options={
                'db_table': 'cuenta',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=200)),
                ('fechaNac', models.DateField()),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dniPersona', models.IntegerField()),
                ('idCuenta', models.IntegerField()),
            ],
            options={
                'db_table': 'propietario',
            },
        ),
    ]
