# Generated by Django 3.1.7 on 2021-10-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='dniPersona',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
