# Generated by Django 3.1.7 on 2021-10-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0002_cuenta_dnipersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroCuenta', models.IntegerField()),
                ('tipo_tarjeta', models.CharField(choices=[('Credito', 'Credito'), ('Debito', 'Debito')], max_length=12)),
                ('limite_tarjeta', models.CharField(blank=True, choices=[('100000', '100000'), ('70000', '70000'), ('50000', '50000'), ('30000', '30000')], max_length=12)),
                ('saldo', models.FloatField()),
            ],
            options={
                'db_table': 'tarjeta',
            },
        ),
    ]
